### ISSUE TITLE
Fix Admin View Users table

### ISSUE THREAD

**Issue by genesisb17** [revaturelabs/rideshare-client#302]
![image](https://user-images.githubusercontent.com/14156684/56687978-7fb95480-66a5-11e9-8817-15121927a865.png)

- Remove ID column
- Change column names -- no need for "User" or "User's" in front of the descriptor
- make "search" "Search"

**Comment by ArchAether** [comment]
Removed the rows containing buttons. Moved button functionality into modals that pop up when you click a table row. Functionality now in dropdown menus.
