### ISSUE TITLE
Change Map starting location 

### ISSUE THREAD

**Issue by genesisb17** [revaturelabs/rideshare-client#303]
- currently, when opening the app the starting location is found via IP address and ipapi.co
- change the starting location to be the user's office location 
- remove the "see drivers near you" button

**Comment by MattLeClair** [comment]
- When users are logged in and go to the map component, the map starts at the address they have provided (ex- user lists 119 west 31st street - CUNY building as their location. The map will now open starting on this location).

- Starting location based off Google Maps/ latitude and longitude.

- "See drivers near you" button removed.
